global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]
  
  - job_name: "windows-exporter"
    static_configs:
    - targets: ["windows-exporter:9182"]
    
rule_files:
  - alert.yml